---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: kubesec-pod
  labels:
    app: kubesec-webhook
    kind: validator
webhooks:
  - name: webhook.kubesc.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/pod"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRRDVIQlNRWmM4Q05UQU5CZ2txaGtpRzl3MEJBUVVGQURBbU1TUXdJZ1lEVlFRRERCdHIKZFdKbGMyVmpMWGRsWW1odmIyc3VhM1ZpWlhObFl5NXpkbU13SGhjTk1UZ3dOekk1TWpFd05URTBXaGNOTVRrdwpOekk1TWpFd05URTBXakFtTVNRd0lnWURWUVFEREJ0cmRXSmxjMlZqTFhkbFltaHZiMnN1YTNWaVpYTmxZeTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaDdsbGxTQkt2dFRGTkNCRm8KWlpuVkpyUXZPZGFvRCtPa3pjOG1LRU9UUDRDMHRBN0JEQ3JRV0xtcFhibU91VU12YldERlE3M3o1MVZrdTlNQQpRdG5ia08rZzhtcFB3ZkhjWk9OVDVvWXJOUGxCeUo1ZDQ3RGRtUHMzUDh2SitXRzdzZ3JacHJ4WXcwZWErNkNECjYxNFI2MGJkcWNKUlRFSkovWTZHeUJLcnlub3BQZjNQQll1ZW1mb2JXSkhZUUtSWUVPNkFER0RmMDdnb0wvSjIKZkpZUjJRemd1WnFWYXA2SGtwcmpHM3RnRHZLMFJ2dHRZbUtoZlVQSTBvY1h6eFU0V0QvS2NTYVVYWE0wSXRHRAp2KzVBR3ZEMU5BMFVEVG1Fdm8zRjNKNzNJTVlYRGZqdUt4ai8wTHJXYU9WU21rRCt0UVBST29GMGliY1RXZjBiCmxUa05BZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFLamhpNWhqUWdFc014ZkYxMyt1VjB3NU5BNFoKUjdIZjc3YXdnNWlQTGp2QnQ1OFZiN3JKc092US9BYzhmZ2VXZS81eldGOGhBTkluSkxnaEtpZFJUdWdVNHdHeApOOThBc0Iyd2dJRzlkSFJZQkhIQ0g0aWdIOUx2cFVFM0NPNGxJc3pyY2g4cjh3NHVxRFdqY3lFRFFlTEIvQklLCk5XRFY3UHU2b1gyYXlaZGhWMFEwT3Vqd0k1Z0pMbEt4VTM0RXpuNVZZQVlGOUlWWEk2WlJvanNpRkdiUmQzTzIKaHVHUGZNTnJpcTIrVWoxVFFXQUZpRUY2MCtxd2VaYTVrNkM1bVQ2NFBTZUd1SE9WOEhjdWhzcytZVVFwZTl1LwphQWlyaEptK2ptSC9lQzdIMEtxUlhtQ0tib1dFQzV1dG91Q2FPL0tyQUl6Myt5bGM0ZzBSaEZxOUtrUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: kubesec-deployment
  labels:
    app: kubesec-webhook
    kind: validator
webhooks:
  - name: webhook.kubesc.io
    clientConfig:
      service:
        name: kubesec-webhook
        namespace: kubesec
        path: "/deployment"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJBQ0NRRDVIQlNRWmM4Q05UQU5CZ2txaGtpRzl3MEJBUVVGQURBbU1TUXdJZ1lEVlFRRERCdHIKZFdKbGMyVmpMWGRsWW1odmIyc3VhM1ZpWlhObFl5NXpkbU13SGhjTk1UZ3dOekk1TWpFd05URTBXaGNOTVRrdwpOekk1TWpFd05URTBXakFtTVNRd0lnWURWUVFEREJ0cmRXSmxjMlZqTFhkbFltaHZiMnN1YTNWaVpYTmxZeTV6CmRtTXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEaDdsbGxTQkt2dFRGTkNCRm8KWlpuVkpyUXZPZGFvRCtPa3pjOG1LRU9UUDRDMHRBN0JEQ3JRV0xtcFhibU91VU12YldERlE3M3o1MVZrdTlNQQpRdG5ia08rZzhtcFB3ZkhjWk9OVDVvWXJOUGxCeUo1ZDQ3RGRtUHMzUDh2SitXRzdzZ3JacHJ4WXcwZWErNkNECjYxNFI2MGJkcWNKUlRFSkovWTZHeUJLcnlub3BQZjNQQll1ZW1mb2JXSkhZUUtSWUVPNkFER0RmMDdnb0wvSjIKZkpZUjJRemd1WnFWYXA2SGtwcmpHM3RnRHZLMFJ2dHRZbUtoZlVQSTBvY1h6eFU0V0QvS2NTYVVYWE0wSXRHRAp2KzVBR3ZEMU5BMFVEVG1Fdm8zRjNKNzNJTVlYRGZqdUt4ai8wTHJXYU9WU21rRCt0UVBST29GMGliY1RXZjBiCmxUa05BZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUZCUUFEZ2dFQkFLamhpNWhqUWdFc014ZkYxMyt1VjB3NU5BNFoKUjdIZjc3YXdnNWlQTGp2QnQ1OFZiN3JKc092US9BYzhmZ2VXZS81eldGOGhBTkluSkxnaEtpZFJUdWdVNHdHeApOOThBc0Iyd2dJRzlkSFJZQkhIQ0g0aWdIOUx2cFVFM0NPNGxJc3pyY2g4cjh3NHVxRFdqY3lFRFFlTEIvQklLCk5XRFY3UHU2b1gyYXlaZGhWMFEwT3Vqd0k1Z0pMbEt4VTM0RXpuNVZZQVlGOUlWWEk2WlJvanNpRkdiUmQzTzIKaHVHUGZNTnJpcTIrVWoxVFFXQUZpRUY2MCtxd2VaYTVrNkM1bVQ2NFBTZUd1SE9WOEhjdWhzcytZVVFwZTl1LwphQWlyaEptK2ptSC9lQzdIMEtxUlhtQ0tib1dFQzV1dG91Q2FPL0tyQUl6Myt5bGM0ZzBSaEZxOUtrUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["extensions"]
        apiVersions: ["v1beta1"]
        resources: ["deployments"]
      - operations: [ "CREATE", "UPDATE" ]
        apiGroups: ["apps"]
        apiVersions: ["v1beta1", "v1beta2", "v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        kubesec-validation: enabled
